// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fiap-tech-challenge-api/internal/adapters/http"
	"fiap-tech-challenge-api/internal/adapters/http/handlers"
	"fiap-tech-challenge-api/internal/adapters/http/middlewares/auth"
	"fiap-tech-challenge-api/internal/adapters/repository"
	"fiap-tech-challenge-api/internal/core/usecase"
	"fiap-tech-challenge-api/internal/core/usecase/mapper"
	"fiap-tech-challenge-api/internal/util"
)

// Injectors from wire.go:

func InitializeWebServer() (*http.Server, error) {
	healthCheck := handlers.NewHealthCheck()
	dbConnector := repository.NewMySQLConnector()
	clienteRepo := repository.NewClienteRepo(dbConnector)
	cadastrarClienteUseCase := usecase.NewCadastraCliente(clienteRepo)
	pesquisarClientePorCPF := usecase.NewPesquisarClientePorCpf(clienteRepo)
	validator := util.NewCustomValidator()
	token := auth.NewJwtToken()
	cliente := handlers.NewCliente(cadastrarClienteUseCase, pesquisarClientePorCPF, validator, token)
	produtoRepo := repository.NewProdutoRepo(dbConnector)
	cadastrarProduto := usecase.NewCadastraProduto(produtoRepo)
	pegarProdutoPorCategoria := usecase.NewPegaProdutoPorCategoria(produtoRepo)
	apagarProduto := usecase.NewApagaProduto(produtoRepo)
	atualizarProduto := usecase.NewAtualizaProduto(produtoRepo)
	produto := handlers.NewProduto(validator, cadastrarProduto, pegarProdutoPorCategoria, apagarProduto, atualizarProduto)
	pedidoRepo := repository.NewPedidoRepo(dbConnector)
	pedido := mapper.NewPedidoMapper()
	listarPedidoPorStatus := usecase.NewListaPedidoPorStatus(pedidoRepo, pedido)
	listarTodosPedidos := usecase.NewListaTodosPedidos(pedidoRepo, pedido)
	pedidoProdutoRepo := repository.NewPedidoProdutoRepo(dbConnector)
	filaRepo := repository.NewFilaRepo(dbConnector)
	cadastrarPedido := usecase.NewCadastraPedido(pedidoRepo, pedidoProdutoRepo, pedido, clienteRepo, produtoRepo, filaRepo)
	atualizaStatusPedidoUC := usecase.NewAtualizaStatusPedidoUC(pedidoRepo, filaRepo)
	pegarDetalhePedido := usecase.NewPegaDetalhePedido(pedidoRepo, pedidoProdutoRepo, produtoRepo, clienteRepo, pedido)
	pagamentoRepo := repository.NewPagamentoRepo(dbConnector)
	cadastrarFila := usecase.NewCadastraFila(filaRepo)
	realizarCheckout := usecase.NewRealizaCheckout(pedidoRepo, pagamentoRepo, cadastrarFila)
	handlersPedido := handlers.NewPedido(validator, listarPedidoPorStatus, listarTodosPedidos, cadastrarPedido, atualizaStatusPedidoUC, pegarDetalhePedido, realizarCheckout, cadastrarFila, token)
	pesquisaPagamento := usecase.NewPesquisaPagamento(pedidoRepo, pagamentoRepo)
	pagamento := handlers.NewPagamento(pesquisaPagamento, validator, token)
	login := handlers.NewLogin(pesquisarClientePorCPF, token)
	server := http.NewAPIServer(healthCheck, cliente, produto, handlersPedido, pagamento, login)
	return server, nil
}
